const mockColumns =
  [
    {
      'href': '/api/v2/LifeCycle_CoreVariables/meta/variable',
      'fieldType': 'STRING',
      'name': 'variable',
      'label': 'Variable',
      'description': 'Short name of the variable (should not include spaces)',
      'attributes': [],
      'maxLength': 255,
      'auto': false,
      'nillable': false,
      'readOnly': false,
      'labelAttribute': true,
      'unique': true,
      'visible': true,
      'lookupAttribute': false,
      'isAggregatable': false
    },
    {
      'href': '/api/v2/LifeCycle_CoreVariables/meta/label',
      'fieldType': 'STRING',
      'name': 'label',
      'label': 'Label',
      'description': 'Longer human readable name of the variable',
      'attributes': [],
      'maxLength': 255,
      'auto': false,
      'nillable': false,
      'readOnly': false,
      'labelAttribute': false,
      'unique': false,
      'visible': true,
      'lookupAttribute': false,
      'isAggregatable': false
    },
    {
      'href': '/api/v2/LifeCycle_CoreVariables/meta/datatype',
      'fieldType': 'CATEGORICAL',
      'name': 'datatype',
      'label': 'Data type',
      'attributes': [],
      'refEntity': {
        'href': '/api/v2/LifeCycle_DataTypes',
        'hrefCollection': '/api/v2/LifeCycle_DataTypes',
        'name': 'LifeCycle_DataTypes',
        'label': 'Data types',
        'description': 'Datetype of the variable',
        'attributes': [
          {
            'href': '/api/v2/LifeCycle_DataTypes/meta/id',
            'fieldType': 'STRING',
            'name': 'id',
            'label': 'ID',
            'attributes': [],
            'maxLength': 255,
            'auto': false,
            'nillable': false,
            'readOnly': true,
            'labelAttribute': false,
            'unique': true,
            'visible': false,
            'lookupAttribute': false,
            'isAggregatable': false
          },
          {
            'href': '/api/v2/LifeCycle_DataTypes/meta/label',
            'fieldType': 'STRING',
            'name': 'label',
            'label': 'Label',
            'attributes': [],
            'maxLength': 255,
            'auto': false,
            'nillable': false,
            'readOnly': false,
            'labelAttribute': true,
            'unique': false,
            'visible': true,
            'lookupAttribute': true,
            'isAggregatable': false
          }
        ],
        'labelAttribute': 'label',
        'idAttribute': 'id',
        'lookupAttributes': [
          'label'
        ],
        'isAbstract': false,
        'writable': false,
        'languageCode': 'en'
      },
      'auto': false,
      'nillable': false,
      'readOnly': false,
      'labelAttribute': false,
      'unique': false,
      'visible': true,
      'lookupAttribute': false,
      'isAggregatable': false
    },
    {
      'href': '/api/v2/LifeCycle_CoreVariables/meta/values',
      'fieldType': 'TEXT',
      'name': 'values',
      'label': 'Values',
      'description': 'Acceptable values for the variable.',
      'attributes': [],
      'maxLength': 65535,
      'auto': false,
      'nillable': true,
      'readOnly': false,
      'labelAttribute': false,
      'unique': false,
      'visible': true,
      'lookupAttribute': false,
      'isAggregatable': false
    },
    {
      'href': '/api/v2/LifeCycle_CoreVariables/meta/unit',
      'fieldType': 'CATEGORICAL',
      'name': 'unit',
      'label': 'Unit',
      'attributes': [],
      'refEntity': {
        'href': '/api/v2/LifeCycle_Units',
        'hrefCollection': '/api/v2/LifeCycle_Units',
        'name': 'LifeCycle_Units',
        'label': 'Units',
        'description': 'Units of measurement',
        'attributes': [
          {
            'href': '/api/v2/LifeCycle_Units/meta/id',
            'fieldType': 'STRING',
            'name': 'id',
            'label': 'ID',
            'attributes': [],
            'maxLength': 255,
            'auto': false,
            'nillable': false,
            'readOnly': true,
            'labelAttribute': false,
            'unique': true,
            'visible': false,
            'lookupAttribute': false,
            'isAggregatable': false
          },
          {
            'href': '/api/v2/LifeCycle_Units/meta/label',
            'fieldType': 'STRING',
            'name': 'label',
            'label': 'Label',
            'attributes': [],
            'maxLength': 255,
            'auto': false,
            'nillable': false,
            'readOnly': false,
            'labelAttribute': true,
            'unique': false,
            'visible': true,
            'lookupAttribute': true,
            'isAggregatable': false
          }
        ],
        'labelAttribute': 'label',
        'idAttribute': 'id',
        'lookupAttributes': [
          'label'
        ],
        'isAbstract': false,
        'writable': false,
        'languageCode': 'en'
      },
      'auto': false,
      'nillable': true,
      'readOnly': false,
      'labelAttribute': false,
      'unique': false,
      'visible': true,
      'lookupAttribute': false,
      'isAggregatable': false
    },
    {
      'href': '/api/v2/LifeCycle_CoreVariables/meta/match',
      'fieldType': 'CATEGORICAL',
      'name': 'match',
      'label': 'Match',
      'description': '',
      'attributes': [],
      'refEntity': {
        'href': '/api/v2/LifeCycle_Status',
        'hrefCollection': '/api/v2/LifeCycle_Status',
        'name': 'LifeCycle_Status',
        'label': 'Status',
        'description': 'Status of the harmonization',
        'attributes': [
          {
            'href': '/api/v2/LifeCycle_Status/meta/id',
            'fieldType': 'STRING',
            'name': 'id',
            'label': 'ID',
            'attributes': [],
            'maxLength': 255,
            'auto': false,
            'nillable': false,
            'readOnly': true,
            'labelAttribute': false,
            'unique': true,
            'visible': false,
            'lookupAttribute': false,
            'isAggregatable': false
          },
          {
            'href': '/api/v2/LifeCycle_Status/meta/label',
            'fieldType': 'STRING',
            'name': 'label',
            'label': 'Label',
            'attributes': [],
            'maxLength': 255,
            'auto': false,
            'nillable': false,
            'readOnly': false,
            'labelAttribute': true,
            'unique': false,
            'visible': true,
            'lookupAttribute': true,
            'isAggregatable': false
          }
        ],
        'labelAttribute': 'label',
        'idAttribute': 'id',
        'lookupAttributes': [
          'label'
        ],
        'isAbstract': false,
        'writable': false,
        'languageCode': 'en'
      },
      'auto': false,
      'nillable': true,
      'readOnly': false,
      'labelAttribute': false,
      'unique': false,
      'visible': true,
      'lookupAttribute': false,
      'isAggregatable': false
    },
    {
      'href': '/api/v2/LifeCycle_CoreVariables/meta/definition',
      'fieldType': 'TEXT',
      'name': 'definition',
      'label': 'Definition',
      'attributes': [],
      'maxLength': 65535,
      'auto': false,
      'nillable': true,
      'readOnly': false,
      'labelAttribute': false,
      'unique': false,
      'visible': true,
      'lookupAttribute': false,
      'isAggregatable': false
    },
    {
      'href': '/api/v2/LifeCycle_CoreVariables/meta/comments',
      'fieldType': 'TEXT',
      'name': 'comments',
      'label': 'Comments',
      'attributes': [],
      'maxLength': 65535,
      'auto': false,
      'nillable': true,
      'readOnly': false,
      'labelAttribute': false,
      'unique': false,
      'visible': true,
      'lookupAttribute': false,
      'isAggregatable': false
    }
  ]

export default {
  mockColumns
}
